### ISSUE TITLE
SolidJS adapter

### ISSUE THREAD

**Issue by mosheduminer** [kolodny/safetest#1]
I'd be interested in creating an adapter for [Solid](https://www.solidjs.com/), what needs to be done to create an adapter?

**Comment by kolodny** [comment]
Awesome! You can take a look at https://github.com/kolodny/safetest/blob/main/src/react.ts it be pretty simple to adjust it for Solid. I see that Solid even has Context, it'd be nice if we can also have a createOverride (in React it uses React Context) mechanism for Solid as well, up to you about that part.
