### ISSUE TITLE
Does it only work for CRA, NEXT and VITE apps

### ISSUE THREAD

**Issue by dasarianudeep** [kolodny/safetest#10]
Hi 

I see the apps in the examples are created via angularcli, next, vite and cra.
How do we run  safetest for applications that are not developed via above .

Thanks
Anudeep D

**Comment by kolodny** [comment]
In theory it should run in all bundlers. The examples given are just a collection of popular bundlers used by different frameworks. Do you have any specific ones you're curious about?

**Comment by kolodny** [comment]
Closing for now, feel free to open if you're hitting an issue with some setup
