### ISSUE TITLE
No @types/safetest ng app

### ISSUE THREAD

**Issue by macorifice** [kolodny/safetest#11]
Trying to do some testing with the sample app for Angular and trying to run the command to start the tests tells me that the types are missing

**Comment by macorifice** [comment]
![Screenshot 2024-02-20 at 15 39 01](https://github.com/kolodny/safetest/assets/2563910/c68b97e3-f1f5-4a7c-a659-69140d690ac8)

**Comment by macorifice** [comment]
<img width="897" alt="Screenshot 2024-02-20 at 15 38 38" src="https://github.com/kolodny/safetest/assets/2563910/a0491a01-3611-4105-8b70-415821d2dd11">

**Comment by MartinFerret** [comment]
@macorifice you managed to run the tests without having OPT_URL issues ?

**Comment by kolodny** [comment]
Also I added a top level ng file, perhaps that also fixes the issue

**Comment by kolodny** [comment]
Closing for now, feel free to reopen is the problem persists.
