### ISSUE TITLE
This library "deletes itself" when starting the dev server

### ISSUE THREAD

**Issue by joschan21** [kolodny/safetest#14]
I struggled with this issue for a solid 15 minutes until I found the root cause, and with this issue I hope we can spare other people the problem. The safetest-link plugin for vite only makes sense if directly cloning from this repo, but in all other cases when installing the npm package, it will actually make your app fail.

It will try to copy and paste files over that do not exist, resulting in the library "deleting itself", or clearing the node_modules folder to the point where only an empty lib folder is left whenever you start the dev server. I suggest this is communicated way more clearly.

**Comment by kolodny** [comment]
I added some warning to the config file, hopefully that should prevent others from hitting this issue. Closing for now, feel free to reopen if there are followup issues or if I missed something
