### ISSUE TITLE
Dynamic rendering blocking

### ISSUE THREAD

**Issue by MartinFerret** [kolodny/safetest#16]
When I run my tests, I'm able to do it when it's simple, like that :

![image](https://github.com/kolodny/safetest/assets/90469240/1fbb1982-9fd7-4fdd-8724-ff7817d9b315)

When it involves rendering something, I can't get it working, the page tries to load but doesn't, like that :

![image](https://github.com/kolodny/safetest/assets/90469240/3f8aa88b-5989-4c12-ae0d-e5f5e9e0d853)

![image](https://github.com/kolodny/safetest/assets/90469240/03acabe7-cfa7-4533-b362-8de683cb84a0)

I'm integrating it on a project, in Angular 16.

Is there a specific config to handle this or that causes the crash ?

**Comment by kolodny** [comment]
Usually this is an issue with the bootstrapping code. Your bootstrapping code [should look like this](https://github.com/kolodny/safetest/blob/main/examples/angular-app/src/main.ts#L27-L31). One of the hidden features of SafeTest is you can add `#safetest` to the url, reload the page, and the console should display all the test files and associated tests. [See here for that working in the example angular app](https://safetest-two.vercel.app/angular-app#safetest).
![image](https://github.com/kolodny/safetest/assets/1187604/20ef7760-a5ed-4b58-93a7-bf1104d882a1)


Does that show you all your test files and tests? If not then you probably have something misconfigured in the bootstrapping code.

**Comment by kolodny** [comment]
That error is a red herring, it's fixed in https://github.com/kolodny/safetest/commit/f57bb0f479b9d299288ec28b372027eb4b9752b5#diff-81a6613f09b12b04742d8b6ef9524cac4577d91a2440485d0cacace86f489069R60, it just needs to be released.

Everything should work per your config. Can you create a minimal repo that has the issue?

**Comment by MartinFerret** [comment]
Here it is @kolodny , gave you the rights to access it.

https://github.com/MartinFerret/safetest-error-case

**Comment by kolodny** [comment]
OK, I see the issue was that windows was using `\` while webpack is expecting `/`. I published a fix in version `0.1.13`. Can you let me know if that fixes the issue?

**Comment by MartinFerret** [comment]
Thanks a lot, it resolves the issue on windows !
