### ISSUE TITLE
Doesn't Recognize "@" in NEXT

### ISSUE THREAD

**Issue by haari006** [kolodny/safetest#17]
I'm using Nextjs and it's not recognizing imports with "@" but if i change to traditional import, it does recognize. Is there any way to define the "@" imports for safetest?

` FAIL  src/app/__tests__/spec.safetest.tsx
  ● Test suite failed to run

    Cannot find module '@/app/server-actions/firebase/profile' from 'src/app/_components/profile/profile-form.tsx'

    Require stack:
      src/app/_components/profile/profile-form.tsx      
      src/app/__tests__/spec.safetest.tsx

      3 | import React, { useEffect, useRef, useState } from "react";
      4 | import { UserCircleIcon } from "@heroicons/react/20/solid";
    > 5 | import {
        | ^
      6 |   update,
      7 |   userDetails,
      8 |   verifyEmail,

      at Resolver.resolveModule (../../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/app/_components/profile/profile-form.tsx:5:1)
      at Object.<anonymous> (src/app/__tests__/spec.safetest.tsx:4:1)
      at TestScheduler.scheduleTests (../../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../../node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.275 s`

**Comment by Urriel** [comment]
Hi @kolodny,

In jest we can specify name mappers like this.
```
moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  }
```

**Comment by kolodny** [comment]
@Urriel Good point. So digging in a bit more, it seems that just using the setup from the [NextJS docs](https://nextjs.org/docs/app/building-your-application/testing/jest#manual-setup) actually takes care of that alias. I updated the NextJS example to have this alias set using [Vitest](https://github.com/kolodny/safetest/commit/0df06d695ae3fdb71d10d759b559b659cbc242fd#diff-697b60b426bb905f5c84457ef78be0eabff6eecd8e68c33e4002b2338d6f4dc5) as well as [Jest](https://github.com/kolodny/safetest/commit/7c08abe0cdc3ca89e8115469f4f219ed0e4fd00e)

**Comment by haari006** [comment]
@kolodny Thanks man
