### ISSUE TITLE
Serialized error NextJS Windows 

### ISSUE THREAD

**Issue by JavierCisneros** [kolodny/safetest#21]
When running the test using command  `pnpm run safetest` got the error on windows `Serialized Error: { input: '${OPT_URL:-http://localhost:3000/next-app/}', code: 'ERR_INVALID_URL' }`

**Comment by JavierCisneros** [comment]
I needed to change the command when running on Windows. I made it work by changing the command in package.json to: `"safetest": "set OPT_URL=http://localhost:3000 && vitest --config vite.safetest.config.mts",` "Instead of the command in the example for Next.js: "`"safetest": "cross-env OPT_URL=${OPT_URL:-http://localhost:3000/next-app/} vitest --config vite.safetest.config.mts",`

**Comment by kolodny** [comment]
Yeah, this is due to Windows not knowing how to deal with this style of bash statements. See https://github.com/kentcdodds/cross-env/issues/140 for more details
