### ISSUE TITLE
Technical reason for createOverride to rely on React Context.

### ISSUE THREAD

**Issue by bricejar** [kolodny/safetest#24]
Hi, 

What is the technical reason for **createOverride** to rely on react Context ? 

A pure vanilla js version would allow to use it outside of a render cycle and it would make it work with any framework too.

**Comment by kolodny** [comment]
There isn't a strong reason, it just fits well with the React ecosystem. I'd be open to a proposal for a more generic solution if it doesn't increase end user complexity
